name: "Windows Release Nightly pytorch"

on:
  workflow_dispatch:
    inputs:
      cu:
        description: 'cuda version'
        required: true
        type: string
        default: "124"

      python_minor:
        description: 'python minor version'
        required: true
        type: string
        default: "12"

      python_patch:
        description: 'python patch version'
        required: true
        type: string
        default: "3"
#  push:
#    branches:
#      - master

jobs:
  build:
    permissions:
        contents: "write"
        packages: "write"
        pull-requests: "read"
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
            persist-credentials: false
        - uses: actions/setup-python@v4
          with:
            python-version: 3.${{ inputs.python_minor }}.${{ inputs.python_patch }}
        - shell: bash
          run: |
            cd ..
            cp -r kaonashiUI kaonashiUI_copy
            curl https://www.python.org/ftp/python/3.${{ inputs.python_minor }}.${{ inputs.python_patch }}/python-3.${{ inputs.python_minor }}.${{ inputs.python_patch }}-embed-amd64.zip -o python_embeded.zip
            unzip python_embeded.zip -d python_embeded
            cd python_embeded
            echo 'import site' >> ./python3${{ inputs.python_minor }}._pth
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            ./python.exe get-pip.py
            python -m pip wheel torch torchvision torchaudio mpmath==1.3.0 numpy==1.26.4 --pre --extra-index-url https://download.pytorch.org/whl/nightly/cu${{ inputs.cu }} -r ../kaonashiUI/requirements.txt pygit2 -w ../temp_wheel_dir
            ls ../temp_wheel_dir
            ./python.exe -s -m pip install --pre ../temp_wheel_dir/*
            sed -i '1i../kaonashiUI' ./python3${{ inputs.python_minor }}._pth
            cd ..

            git clone https://github.com/kaonashianonymous/taesd
            cp taesd/*.pth ./kaonashiUI_copy/models/vae_approx/

            mkdir kaonashiUI_windows_portable_nightly_pytorch
            mv python_embeded kaonashiUI_windows_portable_nightly_pytorch
            mv kaonashiUI_copy kaonashiUI_windows_portable_nightly_pytorch/kaonashiUI

            cd kaonashiUI_windows_portable_nightly_pytorch

            mkdir update
            cp -r kaonashiUI/.ci/update_windows/* ./update/
            cp -r kaonashiUI/.ci/windows_base_files/* ./

            echo "call update_kaonashiui.bat nopause
            ..\python_embeded\python.exe -s -m pip install --upgrade --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cu${{ inputs.cu }} -r ../kaonashiUI/requirements.txt pygit2
            pause" > ./update/update_kaonashiui_and_python_dependencies.bat
            cd ..

            "C:\Program Files\7-Zip\7z.exe" a -t7z -m0=lzma -mx=8 -mfb=64 -md=32m -ms=on -mf=BCJ2 kaonashiUI_windows_portable_nightly_pytorch.7z kaonashiUI_windows_portable_nightly_pytorch
            mv kaonashiUI_windows_portable_nightly_pytorch.7z kaonashiUI/kaonashiUI_windows_portable_nvidia_or_cpu_nightly_pytorch.7z

            cd kaonashiUI_windows_portable_nightly_pytorch
            python_embeded/python.exe -s kaonashiUI/main.py --quick-test-for-ci --cpu

            ls

        - name: Upload binaries to release
          uses: svenstaro/upload-release-action@v2
          with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: kaonashiUI_windows_portable_nvidia_or_cpu_nightly_pytorch.7z
                tag: "latest"
                overwrite: true
